export enum Tag {
  // Engineering & Tech
  Development = 'development',
  Frontend = 'frontend',
  Backend = 'backend',
  Fullstack = 'fullstack',
  Mobile = 'mobile',
  DevOps = 'devops',
  DataScience = 'data-science',
  MachineLearning = 'machine-learning',
  AI = 'ai',
  Cloud = 'cloud',
  Security = 'security',
  Testing = 'testing',
  QA = 'qa',
  GameDev = 'game-dev',
  Embedded = 'embedded',
  IoT = 'iot',
  Robotics = 'robotics',
  Blockchain = 'blockchain',
  ARVR = 'ar-vr',
  OpenSource = 'open-source',
  Documentation = 'documentation',
  Accessibility = 'accessibility',
  Localization = 'localization',

  // Design & Creativity
  Creativity = 'creativity',
  Design = 'design',
  UIUX = 'ui-ux',
  GraphicDesign = 'graphic-design',
  Illustration = 'illustration',
  Motion = 'motion',
  ThreeD = '3d',
  Photography = 'photography',
  Video = 'video',
  Animation = 'animation',
  Branding = 'branding',
  Writing = 'writing',
  Content = 'content',
  Blogging = 'blogging',

  // Product & Business
  Product = 'product',
  ProjectManagement = 'project-management',
  Marketing = 'marketing',
  Growth = 'growth',
  SEO = 'seo',
  Analytics = 'analytics',
  Finance = 'finance',
  Operations = 'operations',
  HR = 'hr',
  Sales = 'sales',
  Entrepreneurship = 'entrepreneurship',
  CustomerSuccess = 'customer-success',
  Support = 'support',
  Compliance = 'compliance',
  Legal = 'legal',

  // Education & Research
  Education = 'education',
  Research = 'research',
  Science = 'science',

  // Health, Fitness & Sport
  Health = 'health',
  Wellness = 'wellness',
  Nutrition = 'nutrition',
  Fitness = 'fitness',
  Sport = 'sport',
  Running = 'running',
  Cycling = 'cycling',
  Football = 'football',
  Basketball = 'basketball',
  Tennis = 'tennis',
  Yoga = 'yoga',
  Esports = 'esports',

  // Lifestyle & Culture
  Music = 'music',
  Film = 'film',
  Literature = 'literature',
  Cooking = 'cooking',
  Food = 'food',
  Travel = 'travel',
  Environment = 'environment',
  Sustainability = 'sustainability',
  Community = 'community',
  Volunteering = 'volunteering'
}

export const ALL_TAGS: Tag[] = Object.values(Tag);

export function labelOf(tag: Tag): string {
  const special: Record<Tag, string> = {
    [Tag.UIUX]: 'UI/UX',
    [Tag.AI]: 'AI',
    [Tag.QA]: 'QA',
    [Tag.ARVR]: 'AR/VR',
    [Tag.ThreeD]: '3D',
    // fallback handled below
    [Tag.Development]: 'Development',
    [Tag.Frontend]: 'Frontend',
    [Tag.Backend]: 'Backend',
    [Tag.Fullstack]: 'Fullstack',
    [Tag.Mobile]: 'Mobile',
    [Tag.DevOps]: 'DevOps',
    [Tag.DataScience]: 'Data Science',
    [Tag.MachineLearning]: 'Machine Learning',
    [Tag.Cloud]: 'Cloud',
    [Tag.Security]: 'Security',
    [Tag.Testing]: 'Testing',
    [Tag.GameDev]: 'Game Dev',
    [Tag.Embedded]: 'Embedded',
    [Tag.IoT]: 'IoT',
    [Tag.Robotics]: 'Robotics',
    [Tag.Blockchain]: 'Blockchain',
    [Tag.OpenSource]: 'Open Source',
    [Tag.Documentation]: 'Documentation',
    [Tag.Accessibility]: 'Accessibility',
    [Tag.Localization]: 'Localization',
    [Tag.Creativity]: 'Creativity',
    [Tag.Design]: 'Design',
    [Tag.GraphicDesign]: 'Graphic Design',
    [Tag.Illustration]: 'Illustration',
    [Tag.Motion]: 'Motion',
    [Tag.Photography]: 'Photography',
    [Tag.Video]: 'Video',
    [Tag.Animation]: 'Animation',
    [Tag.Branding]: 'Branding',
    [Tag.Writing]: 'Writing',
    [Tag.Content]: 'Content',
    [Tag.Blogging]: 'Blogging',
    [Tag.Product]: 'Product',
    [Tag.ProjectManagement]: 'Project Management',
    [Tag.Marketing]: 'Marketing',
    [Tag.Growth]: 'Growth',
    [Tag.SEO]: 'SEO',
    [Tag.Analytics]: 'Analytics',
    [Tag.Finance]: 'Finance',
    [Tag.Operations]: 'Operations',
    [Tag.HR]: 'HR',
    [Tag.Sales]: 'Sales',
    [Tag.Entrepreneurship]: 'Entrepreneurship',
    [Tag.CustomerSuccess]: 'Customer Success',
    [Tag.Support]: 'Support',
    [Tag.Compliance]: 'Compliance',
    [Tag.Legal]: 'Legal',
    [Tag.Education]: 'Education',
    [Tag.Research]: 'Research',
    [Tag.Science]: 'Science',
    [Tag.Health]: 'Health',
    [Tag.Wellness]: 'Wellness',
    [Tag.Nutrition]: 'Nutrition',
    [Tag.Fitness]: 'Fitness',
    [Tag.Sport]: 'Sport',
    [Tag.Running]: 'Running',
    [Tag.Cycling]: 'Cycling',
    [Tag.Football]: 'Football',
    [Tag.Basketball]: 'Basketball',
    [Tag.Tennis]: 'Tennis',
    [Tag.Yoga]: 'Yoga',
    [Tag.Esports]: 'eSports',
    [Tag.Music]: 'Music',
    [Tag.Film]: 'Film',
    [Tag.Literature]: 'Literature',
    [Tag.Cooking]: 'Cooking',
    [Tag.Food]: 'Food',
    [Tag.Travel]: 'Travel',
    [Tag.Environment]: 'Environment',
    [Tag.Sustainability]: 'Sustainability',
    [Tag.Community]: 'Community',
    [Tag.Volunteering]: 'Volunteering'
  };
  return special[tag] ?? String(tag)
    .replace(/-/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}
